version: '3.1'

services:

  mariadb_app1:
    image: mariadb
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - $DB_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PWD

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080